server:
  port: 8082

spring:
  application:
    name: InventoryService

  datasource:
    url: jdbc:postgresql://localhost:5432/LogiTrack_Inventory_Service
    username: postgres
    password: 28859013
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
