server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LogiTrack_Auth_Service
    username: postgres
    password: 28859013
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: auth-service

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

jwt:
  user_secret: s2v6asadsas1fsde1CSsaf2rewfas902u0aJWsgGIQ7382bfjafqfhqhfo
  user_secret_lifetime: 10m
