server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USERNAME}:${MONGO_PASSWORD}@cluster0.2fd08.mongodb.net/shipping_service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: shipping-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:5432/LogiTrack_Shipping_Service