server:
  port: 8081

spring:
  application:
    name: OrderService

  datasource:
    url: jdbc:postgresql://localhost:5432/LogiTrack_Order_Service
    username: postgres
    password: 28859013
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

jwt:
  user_secret: s2v6asadsas1fsde1CSsaf2rewfas902u0aJWsgGIQ7382bfjafqfhqhfo
  user_secret_lifetime: 10m
